
windowrule = opacity 0.0 override 0.0 override, match:title .*is sharing your screen.*
windowrule = no_focus on, match:title .*is sharing your screen.*
windowrule = move -9999 -9999, match:title .*is sharing your screen.*
