exec-once = dms run
exec-once = wl-clip-persist --clipboard both
# exec-once = playerctld daemon
exec-once = solaar --window=hide
exec-once = [workspace 1 silent] uwsm-app -- brave
exec-once = [workspace 2 silent] uwsm-app -- ghostty
exec-once = uwsm-app -- telegram-desktop

