exec-once = wl-clip-persist --clipboard both
# exec-once = playerctld daemon
exec-once = solaar --window=hide
exec-once = uwsm-app -- brave
exec-once = uwsm-app -- telegram-desktop
exec-once = uwsm-app -- xdg-terminal-exec
exec-once = ~/Downloads/v2rayN-linux-64/v2rayN
exec-once = uwsm-app -- chromium

