# Format: monitor = [port], resolution, position, scale

monitor = HDMI-A-1, 2560x1440@144, 0x0, 1

monitor = eDP-1, 2880x1620@120, 2560x0, 1.5

# Workspace bindings
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
